# Parameters
BATCH_SIZE: 512
LATENT_DIM: 5

# Optimizer parameters
LR_GENERATOR: 0.0001
LR_DISCRIMINATOR: 0.0001


SEED: 42
USE_GPU: True  # True: 'cuda', False: 'cpu'

EXPERIMENT_NAME: 'NormalDistribution'

MODELS_CONFIGURATION:
  GENERATOR:
    fc:
      neurons: [5, 15, 1]
      dropout: [0.0]

  DISCRIMINATOR:
    fc:
      neurons: [1, 25, 1]
      dropout: [0.0]

        # TODO: add batchnorm to the models